/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Healthcheck consumed by Docker, Zabbix, etc.
         *
         *     Returns `{ status, db, uptime_s }`. If the DB is unreachable the endpoint
         *     still returns 200 with `db: "down"` so that clients can distinguish
         *     app-down from db-down — this matches the behaviour described in docs/07.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Callback */
        get: operations["auth_callback_api_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sites */
        get: operations["list_sites_api_sites_get"];
        put?: never;
        /** Create Site */
        post: operations["create_site_api_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site */
        get: operations["get_site_api_sites__site_id__get"];
        /** Update Site */
        put: operations["update_site_api_sites__site_id__put"];
        post?: never;
        /** Delete Site */
        delete: operations["delete_site_api_sites__site_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rooms */
        get: operations["list_rooms_api_rooms_get"];
        put?: never;
        /** Create Room */
        post: operations["create_room_api_rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room */
        get: operations["get_room_api_rooms__room_id__get"];
        /** Update Room */
        put: operations["update_room_api_rooms__room_id__put"];
        post?: never;
        /** Delete Room */
        delete: operations["delete_room_api_rooms__room_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vlans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vlans */
        get: operations["list_vlans_api_vlans_get"];
        put?: never;
        /** Create Vlan */
        post: operations["create_vlan_api_vlans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vlans/{vlan_pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vlan */
        get: operations["get_vlan_api_vlans__vlan_pk__get"];
        /** Update Vlan */
        put: operations["update_vlan_api_vlans__vlan_pk__put"];
        post?: never;
        /** Delete Vlan */
        delete: operations["delete_vlan_api_vlans__vlan_pk__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subnets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subnets */
        get: operations["list_subnets_api_subnets_get"];
        put?: never;
        /** Create Subnet */
        post: operations["create_subnet_api_subnets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subnets/{subnet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subnet */
        get: operations["get_subnet_api_subnets__subnet_id__get"];
        /** Update Subnet */
        put: operations["update_subnet_api_subnets__subnet_id__put"];
        post?: never;
        /** Delete Subnet */
        delete: operations["delete_subnet_api_subnets__subnet_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subnets/{subnet_id}/ips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subnet Ips */
        get: operations["list_subnet_ips_api_subnets__subnet_id__ips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subnets/{subnet_id}/next-free": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Next Free Ip */
        post: operations["next_free_ip_api_subnets__subnet_id__next_free_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ips */
        get: operations["list_ips_api_ips_get"];
        put?: never;
        /** Create Ip */
        post: operations["create_ip_api_ips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ips/{ip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ip */
        get: operations["get_ip_api_ips__ip_id__get"];
        /** Update Ip */
        put: operations["update_ip_api_ips__ip_id__put"];
        post?: never;
        /** Delete Ip */
        delete: operations["delete_ip_api_ips__ip_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_devices_get"];
        put?: never;
        /** Create Device */
        post: operations["create_device_api_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_api_devices__device_id__get"];
        /** Update Device */
        put: operations["update_device_api_devices__device_id__put"];
        post?: never;
        /** Delete Device */
        delete: operations["delete_device_api_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/switches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Switches */
        get: operations["list_switches_api_switches_get"];
        put?: never;
        /** Create Switch */
        post: operations["create_switch_api_switches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/switches/{switch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Switch */
        get: operations["get_switch_api_switches__switch_id__get"];
        /** Update Switch */
        put: operations["update_switch_api_switches__switch_id__put"];
        post?: never;
        /** Delete Switch */
        delete: operations["delete_switch_api_switches__switch_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/switches/{switch_id}/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ports Of Switch */
        get: operations["list_ports_of_switch_api_switches__switch_id__ports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ports/{port_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Port */
        get: operations["get_port_api_ports__port_id__get"];
        /** Update Port */
        put: operations["update_port_api_ports__port_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ports/{port_id}/vlans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Tagged Vlan */
        post: operations["add_tagged_vlan_api_ports__port_id__vlans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ports/{port_id}/vlans/{vlan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Tagged Vlan */
        delete: operations["remove_tagged_vlan_api_ports__port_id__vlans__vlan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Links */
        get: operations["list_links_api_links_get"];
        put?: never;
        /** Create Link */
        post: operations["create_link_api_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Link */
        get: operations["get_link_api_links__link_id__get"];
        put?: never;
        post?: never;
        /** Delete Link */
        delete: operations["delete_link_api_links__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit */
        get: operations["get_audit_api_audit__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global Search */
        get: operations["global_search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topology */
        get: operations["get_topology_api_topology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{entity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Entity */
        post: operations["import_entity_api_imports__entity__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/{entity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Entity */
        get: operations["export_entity_api_exports__entity__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditAction
         * @enum {string}
         */
        AuditAction: "create" | "update" | "delete";
        /** AuditLogRead */
        AuditLogRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number | null;
            action: components["schemas"]["AuditAction"];
            /** Entity */
            entity: string;
            /** Entity Id */
            entity_id: number | null;
            /** Changes */
            changes: {
                [key: string]: unknown;
            } | null;
            /** Ip Address */
            ip_address: string | null;
            /** User Agent */
            user_agent: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_import_entity_api_imports__entity__post */
        Body_import_entity_api_imports__entity__post: {
            /** File */
            file: string;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /** DeviceCreate */
        DeviceCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["DeviceType"];
            /** Vendor */
            vendor?: string | null;
            /** Model */
            model?: string | null;
            /** Serial */
            serial?: string | null;
            /** Room Id */
            room_id?: number | null;
            /** Description */
            description?: string | null;
        };
        /** DeviceRead */
        DeviceRead: {
            /** Name */
            name: string;
            type: components["schemas"]["DeviceType"];
            /** Vendor */
            vendor?: string | null;
            /** Model */
            model?: string | null;
            /** Serial */
            serial?: string | null;
            /** Room Id */
            room_id?: number | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
        };
        /**
         * DeviceType
         * @enum {string}
         */
        DeviceType: "server" | "desktop" | "laptop" | "printer" | "phone" | "ap" | "camera" | "ups" | "other";
        /** DeviceUpdate */
        DeviceUpdate: {
            /** Name */
            name?: string | null;
            type?: components["schemas"]["DeviceType"] | null;
            /** Vendor */
            vendor?: string | null;
            /** Model */
            model?: string | null;
            /** Serial */
            serial?: string | null;
            /** Room Id */
            room_id?: number | null;
            /** Description */
            description?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportErrorRow
         * @description One failure reported by the import — either a parse/validation error
         *     flagged before any DB work, or a constraint violation surfaced during
         *     the apply phase.
         */
        ImportErrorRow: {
            /** Line */
            line: number;
            /** Column */
            column?: string | null;
            /** Value */
            value?: string | null;
            /** Error */
            error: string;
        };
        /** ImportReport */
        ImportReport: {
            /** Parsed Rows */
            parsed_rows: number;
            /** Ok Rows */
            ok_rows: number;
            /** Error Rows */
            error_rows: components["schemas"]["ImportErrorRow"][];
            /** Applied */
            applied: boolean;
        };
        /** IpCreate */
        IpCreate: {
            /** Subnet Id */
            subnet_id: number;
            /**
             * Address
             * @description IPv4 address, e.g. 10.0.30.42
             */
            address: string;
            /** Hostname */
            hostname?: string | null;
            /** Mac */
            mac?: string | null;
            /** Device Id */
            device_id?: number | null;
            status: components["schemas"]["IpStatus"];
            /** Description */
            description?: string | null;
        };
        /** IpRead */
        IpRead: {
            /** Subnet Id */
            subnet_id: number;
            /**
             * Address
             * @description IPv4 address, e.g. 10.0.30.42
             */
            address: string;
            /** Hostname */
            hostname?: string | null;
            /** Mac */
            mac?: string | null;
            /** Device Id */
            device_id?: number | null;
            status: components["schemas"]["IpStatus"];
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * IpStatus
         * @enum {string}
         */
        IpStatus: "reserved" | "assigned" | "dhcp";
        /** IpUpdate */
        IpUpdate: {
            /** Subnet Id */
            subnet_id?: number | null;
            /** Address */
            address?: string | null;
            /** Hostname */
            hostname?: string | null;
            /** Mac */
            mac?: string | null;
            /** Device Id */
            device_id?: number | null;
            status?: components["schemas"]["IpStatus"] | null;
            /** Description */
            description?: string | null;
        };
        /** LinkCreate */
        LinkCreate: {
            /** Port A Id */
            port_a_id: number;
            /** Port B Id */
            port_b_id: number;
            link_type: components["schemas"]["LinkType"];
            /** Speed Mbps */
            speed_mbps?: number | null;
            /** Description */
            description?: string | null;
        };
        /** LinkRead */
        LinkRead: {
            /** Port A Id */
            port_a_id: number;
            /** Port B Id */
            port_b_id: number;
            link_type: components["schemas"]["LinkType"];
            /** Speed Mbps */
            speed_mbps?: number | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
        };
        /**
         * LinkType
         * @enum {string}
         */
        LinkType: "copper" | "fiber" | "dac" | "virtual";
        /** NextFreeIpResponse */
        NextFreeIpResponse: {
            /** Address */
            address: string;
        };
        /** Page[AuditLogRead] */
        Page_AuditLogRead_: {
            /** Items */
            items: components["schemas"]["AuditLogRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[DeviceRead] */
        Page_DeviceRead_: {
            /** Items */
            items: components["schemas"]["DeviceRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[IpRead] */
        Page_IpRead_: {
            /** Items */
            items: components["schemas"]["IpRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[LinkRead] */
        Page_LinkRead_: {
            /** Items */
            items: components["schemas"]["LinkRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[PortRead] */
        Page_PortRead_: {
            /** Items */
            items: components["schemas"]["PortRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[RoomRead] */
        Page_RoomRead_: {
            /** Items */
            items: components["schemas"]["RoomRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[SiteRead] */
        Page_SiteRead_: {
            /** Items */
            items: components["schemas"]["SiteRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[SubnetRead] */
        Page_SubnetRead_: {
            /** Items */
            items: components["schemas"]["SubnetRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[SwitchRead] */
        Page_SwitchRead_: {
            /** Items */
            items: components["schemas"]["SwitchRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[VlanRead] */
        Page_VlanRead_: {
            /** Items */
            items: components["schemas"]["VlanRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * PortAdminStatus
         * @enum {string}
         */
        PortAdminStatus: "up" | "down";
        /**
         * PortMode
         * @enum {string}
         */
        PortMode: "access" | "trunk" | "hybrid" | "disabled";
        /** PortRead */
        PortRead: {
            /** Switch Id */
            switch_id: number;
            /** Number */
            number: number;
            /** Label */
            label?: string | null;
            /** @default access */
            mode: components["schemas"]["PortMode"];
            /** Native Vlan Id */
            native_vlan_id?: number | null;
            /** @default up */
            admin_status: components["schemas"]["PortAdminStatus"];
            /** Connected Device Id */
            connected_device_id?: number | null;
            /** Connected Ip Id */
            connected_ip_id?: number | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
        };
        /**
         * PortUpdate
         * @description All editable fields. `switch_id` and `number` are immutable here —
         *     ports are created automatically with their switch.
         */
        PortUpdate: {
            /** Label */
            label?: string | null;
            mode?: components["schemas"]["PortMode"] | null;
            /** Native Vlan Id */
            native_vlan_id?: number | null;
            admin_status?: components["schemas"]["PortAdminStatus"] | null;
            /** Connected Device Id */
            connected_device_id?: number | null;
            /** Connected Ip Id */
            connected_ip_id?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** RoomCreate */
        RoomCreate: {
            /** Site Id */
            site_id: number;
            /** Code */
            code: string;
            /** Description */
            description?: string | null;
        };
        /** RoomRead */
        RoomRead: {
            /** Site Id */
            site_id: number;
            /** Code */
            code: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
        };
        /** RoomUpdate */
        RoomUpdate: {
            /** Site Id */
            site_id?: number | null;
            /** Code */
            code?: string | null;
            /** Description */
            description?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchResult"][];
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Type
             * @enum {string}
             */
            type: "ip" | "device" | "switch" | "port";
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Context */
            context?: string | null;
        };
        /** SiteCreate */
        SiteCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
        };
        /** SiteRead */
        SiteRead: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SiteUpdate */
        SiteUpdate: {
            /** Code */
            code?: string | null;
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
        };
        /** SubnetCreate */
        SubnetCreate: {
            /**
             * Cidr
             * @description IPv4 CIDR, e.g. 10.0.30.0/24
             */
            cidr: string;
            /** Gateway */
            gateway?: string | null;
            /** Vlan Id */
            vlan_id?: number | null;
            /** Site Id */
            site_id: number;
            /** Description */
            description?: string | null;
            /**
             * Dhcp Enabled
             * @default false
             */
            dhcp_enabled: boolean;
            /** Dhcp Range Start */
            dhcp_range_start?: string | null;
            /** Dhcp Range End */
            dhcp_range_end?: string | null;
        };
        /**
         * SubnetIpEntry
         * @description One row in the GET /api/subnets/{id}/ips response.
         *
         *     `status` may be one of the stored statuses (`reserved`, `assigned`, `dhcp`)
         *     OR the synthetic `"free"` for addresses that have no row in `ips`.
         */
        SubnetIpEntry: {
            /** Address */
            address: string;
            /** Status */
            status: string;
            /** Hostname */
            hostname?: string | null;
            /** Mac */
            mac?: string | null;
            /** Device Id */
            device_id?: number | null;
            /** Description */
            description?: string | null;
        };
        /** SubnetIpsResponse */
        SubnetIpsResponse: {
            subnet: components["schemas"]["SubnetRead"];
            /** Ips */
            ips: components["schemas"]["SubnetIpEntry"][];
        };
        /** SubnetRead */
        SubnetRead: {
            /**
             * Cidr
             * @description IPv4 CIDR, e.g. 10.0.30.0/24
             */
            cidr: string;
            /** Gateway */
            gateway?: string | null;
            /** Vlan Id */
            vlan_id?: number | null;
            /** Site Id */
            site_id: number;
            /** Description */
            description?: string | null;
            /**
             * Dhcp Enabled
             * @default false
             */
            dhcp_enabled: boolean;
            /** Dhcp Range Start */
            dhcp_range_start?: string | null;
            /** Dhcp Range End */
            dhcp_range_end?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SubnetUpdate */
        SubnetUpdate: {
            /** Cidr */
            cidr?: string | null;
            /** Gateway */
            gateway?: string | null;
            /** Vlan Id */
            vlan_id?: number | null;
            /** Site Id */
            site_id?: number | null;
            /** Description */
            description?: string | null;
            /** Dhcp Enabled */
            dhcp_enabled?: boolean | null;
            /** Dhcp Range Start */
            dhcp_range_start?: string | null;
            /** Dhcp Range End */
            dhcp_range_end?: string | null;
        };
        /** SwitchCreate */
        SwitchCreate: {
            /** Name */
            name: string;
            /** Vendor */
            vendor?: string | null;
            /** Model */
            model?: string | null;
            /** Serial */
            serial?: string | null;
            /** Management Ip */
            management_ip?: string | null;
            /** Room Id */
            room_id?: number | null;
            /** Rack Position */
            rack_position?: string | null;
            /** Port Count */
            port_count: number;
            /** Firmware Version */
            firmware_version?: string | null;
            /** Snmp Community */
            snmp_community?: string | null;
            /** Description */
            description?: string | null;
        };
        /** SwitchRead */
        SwitchRead: {
            /** Name */
            name: string;
            /** Vendor */
            vendor?: string | null;
            /** Model */
            model?: string | null;
            /** Serial */
            serial?: string | null;
            /** Management Ip */
            management_ip?: string | null;
            /** Room Id */
            room_id?: number | null;
            /** Rack Position */
            rack_position?: string | null;
            /** Port Count */
            port_count: number;
            /** Firmware Version */
            firmware_version?: string | null;
            /** Snmp Community */
            snmp_community?: string | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SwitchUpdate */
        SwitchUpdate: {
            /** Name */
            name?: string | null;
            /** Vendor */
            vendor?: string | null;
            /** Model */
            model?: string | null;
            /** Serial */
            serial?: string | null;
            /** Management Ip */
            management_ip?: string | null;
            /** Room Id */
            room_id?: number | null;
            /** Rack Position */
            rack_position?: string | null;
            /** Firmware Version */
            firmware_version?: string | null;
            /** Snmp Community */
            snmp_community?: string | null;
            /** Description */
            description?: string | null;
        };
        /** TaggedVlanAdd */
        TaggedVlanAdd: {
            /** Vlan Id */
            vlan_id: number;
        };
        /** TopologyEdge */
        TopologyEdge: {
            data: components["schemas"]["TopologyEdgeData"];
        };
        /** TopologyEdgeData */
        TopologyEdgeData: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Link Type */
            link_type: string;
            /** Speed Mbps */
            speed_mbps?: number | null;
            /** Port A */
            port_a: number;
            /** Port B */
            port_b: number;
        };
        /** TopologyNode */
        TopologyNode: {
            data: components["schemas"]["TopologyNodeData"];
        };
        /** TopologyNodeData */
        TopologyNodeData: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Type
             * @default switch
             * @constant
             */
            type: "switch";
            /** Vendor */
            vendor?: string | null;
            /** Model */
            model?: string | null;
            /** Management Ip */
            management_ip?: string | null;
            /** Room Id */
            room_id?: number | null;
            /** Ports Total */
            ports_total: number;
        };
        /** TopologyResponse */
        TopologyResponse: {
            /** Nodes */
            nodes: components["schemas"]["TopologyNode"][];
            /** Edges */
            edges: components["schemas"]["TopologyEdge"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VlanCreate */
        VlanCreate: {
            /** Vlan Id */
            vlan_id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Color */
            color?: string | null;
        };
        /** VlanRead */
        VlanRead: {
            /** Vlan Id */
            vlan_id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Color */
            color?: string | null;
            /** Id */
            id: number;
        };
        /** VlanUpdate */
        VlanUpdate: {
            /** Vlan Id */
            vlan_id?: number | null;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Color */
            color?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_callback_api_auth_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_sites_api_sites_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SiteRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_site_api_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_api_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_site_api_sites__site_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_site_api_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rooms_api_rooms_get: {
        parameters: {
            query?: {
                site_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RoomRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_room_api_rooms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_room_api_rooms__room_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_room_api_rooms__room_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_room_api_rooms__room_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vlans_api_vlans_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_VlanRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vlan_api_vlans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vlan_api_vlans__vlan_pk__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vlan_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vlan_api_vlans__vlan_pk__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vlan_pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vlan_api_vlans__vlan_pk__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vlan_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subnets_api_subnets_get: {
        parameters: {
            query?: {
                site_id?: number | null;
                vlan_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SubnetRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subnet_api_subnets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubnetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubnetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subnet_api_subnets__subnet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subnet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubnetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subnet_api_subnets__subnet_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subnet_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubnetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubnetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subnet_api_subnets__subnet_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subnet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subnet_ips_api_subnets__subnet_id__ips_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subnet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubnetIpsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_free_ip_api_subnets__subnet_id__next_free_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subnet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextFreeIpResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ips_api_ips_get: {
        parameters: {
            query?: {
                subnet_id?: number | null;
                status?: components["schemas"]["IpStatus"] | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_IpRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ip_api_ips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IpCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ip_api_ips__ip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ip_api_ips__ip_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IpUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ip_api_ips__ip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_devices_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["DeviceType"] | null;
                room_id?: number | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DeviceRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device_api_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_api_devices__device_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_api_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_switches_api_switches_get: {
        parameters: {
            query?: {
                room_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SwitchRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_switch_api_switches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwitchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_switch_api_switches__switch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                switch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwitchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_switch_api_switches__switch_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                switch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwitchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_switch_api_switches__switch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                switch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ports_of_switch_api_switches__switch_id__ports_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                switch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PortRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_port_api_ports__port_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_port_api_ports__port_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_tagged_vlan_api_ports__port_id__vlans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaggedVlanAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_tagged_vlan_api_ports__port_id__vlans__vlan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_id: number;
                vlan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_links_api_links_get: {
        parameters: {
            query?: {
                switch_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LinkRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_link_api_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_link_api_links__link_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_link_api_links__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_audit_get: {
        parameters: {
            query?: {
                entity?: string | null;
                entity_id?: number | null;
                user_id?: number | null;
                from?: string | null;
                to?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditLogRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_api_audit__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    global_search_api_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topology_api_topology_get: {
        parameters: {
            query?: {
                site_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_entity_api_imports__entity__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_entity_api_imports__entity__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_entity_api_exports__entity__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
