/**
 * Placeholder. Real types are generated by `npm run gen:types`, which calls
 * `openapi-typescript http://localhost:8000/api/openapi.json -o src/api/schema.d.ts`.
 *
 * Run that command once the backend is up; it will overwrite this file with the
 * full typed schema (paths, components, operations) keyed off the FastAPI spec.
 */

export interface paths {}
export interface components {
  schemas: Record<string, unknown>
}
export interface operations {}
